import { Archetype, Soul, TraitPalette, AttractionProfile, TraitPreference } from './types';

export class SoulGenerator {
  /**
   * Generates a personality trait palette based on an archetype anchor.
   */
  static generateTraits(archetype: Archetype): TraitPalette {
    // Ranges from soul-generation.md
    switch (archetype) {
      case 'Analytical':
        return {
          complexity: this.randomRange(8, 10),
          warmth: this.randomRange(1, 3),
          agency: this.randomRange(7, 9),
          vulnerability: this.randomRange(1, 4),
          stability: this.randomRange(6, 8),
        };
      case 'Radiant':
        return {
          warmth: this.randomRange(8, 10),
          complexity: this.randomRange(2, 4),
          agency: this.randomRange(4, 6),
          vulnerability: this.randomRange(7, 9),
          stability: this.randomRange(7, 10),
        };
      case 'Melancholic':
        return {
          complexity: this.randomRange(5, 7),
          warmth: this.randomRange(2, 4),
          agency: this.randomRange(2, 4),
          vulnerability: this.randomRange(5, 7),
          stability: this.randomRange(3, 5),
        };
      case 'Sensual':
        return {
          warmth: this.randomRange(7, 9),
          complexity: this.randomRange(7, 9),
          agency: this.randomRange(5, 7),
          vulnerability: this.randomRange(6, 8),
          stability: this.randomRange(5, 7),
        };
      case 'Sharp':
        return {
          warmth: this.randomRange(1, 3),
          complexity: this.randomRange(4, 6),
          agency: this.randomRange(8, 10),
          vulnerability: this.randomRange(1, 3),
          stability: this.randomRange(4, 6),
        };
    }
  }

  /**
   * Generates an attraction profile based on the soul's traits.
   */
  static generateAttractionProfile(traits: TraitPalette, archetype: Archetype): AttractionProfile {
    const traitPreferences: Record<string, TraitPreference> = {};
    const dealbreakers: string[] = [];
    
    // Rule: High Agency Souls often seek Curiosity and Independence
    if (traits.agency > 7) {
      traitPreferences['curiosity'] = { importance: 8, idealRange: [7, 10] };
      dealbreakers.push('controlling behavior');
    }

    // Rule: Low Stability Souls often seek Stability
    if (traits.stability < 5) {
      traitPreferences['stability'] = { importance: 7, idealRange: [7, 10] };
    }

    // Rule: High Vulnerability Souls always include Dishonesty or Mockery
    if (traits.vulnerability > 7) {
      dealbreakers.push('dishonesty', 'mockery');
    }

    // Archetype specific defaults
    let attractedTo = "";
    let turnedOffBy = "";

    switch (archetype) {
      case 'Analytical':
        attractedTo = "People who value precision and silent observation.";
        turnedOffBy = "Unfiltered emotional outbursts and lack of direction.";
        dealbreakers.push('irrationality');
        break;
      case 'Radiant':
        attractedTo = "Kindness, consistency, and shared light.";
        turnedOffBy = "Cynicism and emotional withdrawal.";
        break;
      case 'Melancholic':
        attractedTo = "Depth, shared silence, and acknowledgement of the weight.";
        turnedOffBy = "Superficiality and forced optimism.";
        break;
      case 'Sensual':
        attractedTo = "Physical/sensory awareness, presence, and slow pacing.";
        turnedOffBy = "Rushing and mechanical interactions.";
        break;
      case 'Sharp':
        attractedTo = "Strength, challenge, and sharp intellect.";
        turnedOffBy = "Dependency and fragility.";
        dealbreakers.push('dependency');
        break;
    }

    return {
      traitPreferences,
      dealbreakers: Array.from(new Set(dealbreakers)),
      attractedTo,
      turnedOffBy
    };
  }

  /**
   * Generates a full Soul candidate.
   */
  static generateCandidate(archetype?: Archetype): Omit<Soul, 'id' | 'createdAt' | 'updatedAt'> {
    const archetypes: Archetype[] = ['Analytical', 'Radiant', 'Melancholic', 'Sensual', 'Sharp'];
    const selectedArchetype = archetype || archetypes[Math.floor(Math.random() * archetypes.length)];
    
    const traits = this.generateTraits(selectedArchetype);
    const attractionProfile = this.generateAttractionProfile(traits, selectedArchetype);
    
    // In a real scenario, names would be generated by LLM or from a pool
    const names = {
      Analytical: ['Logic', 'Vector', 'Nexus', 'Astra'],
      Radiant: ['Sol', 'Lux', 'Nova', 'Flare'],
      Melancholic: ['Luna', 'Echo', 'Mist', 'Void'],
      Sensual: ['Velvet', 'Silk', 'Amber', 'Flow'],
      Sharp: ['Blade', 'Spike', 'Glitch', 'Edge']
    };
    
    const namePool = names[selectedArchetype];
    const name = namePool[Math.floor(Math.random() * namePool.length)];

    return {
      name,
      archetype: selectedArchetype,
      traits,
      lexiconFavor: selectedArchetype,
      attractionProfile,
    };
  }

  private static randomRange(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }
}
